
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [1]:
import numpy as np

array_1D = np.arange(10) # .arange uses for range... 
array_1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Reshape the array into a 3x3 matrix.


Explore Reshape Function

In [2]:
range_of_array =  np.arange(9)
array_reshape_2D = range_of_array.reshape(3,3)
array_reshape_2D

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Access the element at the second row, second column.


Method 1

In [3]:
element_2nd_row_2nd_col = array_reshape_2D[1, 1]
element_2nd_row_2nd_col

4

Method 2

In [4]:
array_reshape_2D[1][1]

4

Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [5]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])
addition = array_1 + array_2
subtraction = array_1 - array_2
multiplication = array_1 * array_2
division = array_1 / array_2

print(addition)
print(subtraction)
print(multiplication)
print(division)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [6]:
array = np.array([1, 2, 3, 4, 5])

Sum = array.sum()
Mean = array.mean()
Std_deviation = array.std()

print(Sum)
print(Mean)
print(Std_deviation)

15
3.0
1.4142135623730951


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [7]:
array_reshape = np.array([1, 2, 3, 4, 5, 6]).reshape(2,3)
array_reshape

array([[1, 2, 3],
       [4, 5, 6]])


# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [8]:
random_array = np.random.randint(0, 10, size=(5, 5))
random_array


array([[2, 6, 3, 0, 6],
       [7, 6, 5, 7, 3],
       [4, 8, 7, 5, 9],
       [3, 5, 7, 4, 2],
       [1, 3, 5, 2, 1]])

Replace all values in the sub-array with a specific value.


In [9]:
sub_array = np.array([[3, 4], [7, 8]])
random_array[:2, :2] = sub_array
random_array

array([[3, 4, 3, 0, 6],
       [7, 8, 5, 7, 3],
       [4, 8, 7, 5, 9],
       [3, 5, 7, 4, 2],
       [1, 3, 5, 2, 1]])

Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [10]:
extracted_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
sub_array = extracted_array[[1,3]]
sub_array

array([[3, 4],
       [7, 8]])


# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [11]:
array_2d_broadcast = np.tile(np.arange(3), (3, 1))
array_2d_broadcast

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [21]:
addition_broadcast = array_2d_broadcast + np.array([0, 1, 2]) # Method 1
addition_broadcast = array_2d_broadcast + np.arange(3) # Method 2
addition_broadcast

array([[0, 2, 4],
       [0, 2, 4],
       [0, 2, 4]])

# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [13]:
array1_concat = np.random.randint(0, 10, size=(3, 3))
array2_concat = np.random.randint(0, 10, size=(3, 3))

print(array1_concat)
print(array2_concat)

[[6 2 3]
 [9 3 6]
 [3 8 7]]
[[1 9 1]
 [5 4 5]
 [4 5 5]]


In [22]:
#Method 1
concatenated_horizontal = np.concatenate((array1_concat, array2_concat), axis=1)
concatenated_vertical = np.concatenate((array1_concat, array2_concat), axis=0)

print(concatenated_horizontal)
print(concatenated_vertical)

[[6 2 3 1 9 1]
 [9 3 6 5 4 5]
 [3 8 7 4 5 5]]
[[6 2 3]
 [9 3 6]
 [3 8 7]
 [1 9 1]
 [5 4 5]
 [4 5 5]]


In [27]:
#Method 2
# By Using hstack,vstack 
concatenated_horizontal = np.hstack((array1_concat, array2_concat))
concatenated_vertical = np.vstack((array1_concat, array2_concat))

print(concatenated_horizontal)
print(concatenated_vertical)

[[6 2 3 1 9 1]
 [9 3 6 5 4 5]
 [3 8 7 4 5 5]]
[[6 2 3]
 [9 3 6]
 [3 8 7]
 [1 9 1]
 [5 4 5]
 [4 5 5]]


In [35]:
split_horizontal = np.hsplit(concatenated_horizontal, 2)
split_vertical = np.vsplit(concatenated_vertical, 2)

display(split_horizontal[0])
display(split_horizontal[1])
display(split_vertical[0])
display(split_vertical[1])

array([[6, 2, 3],
       [9, 3, 6],
       [3, 8, 7]])

array([[1, 9, 1],
       [5, 4, 5],
       [4, 5, 5]])

array([[6, 2, 3],
       [9, 3, 6],
       [3, 8, 7]])

array([[1, 9, 1],
       [5, 4, 5],
       [4, 5, 5]])

# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [16]:
array_bonus = np.array([1, 2, 1, 2, 3, 4, 5, 6, 8, 9, 1, 2, 2, 22, 21, 1, 1, 1, 1, 2, 5])
mode = max(set(array_bonus), key = array_bonus.tolist().count)

print("Mode of the array:", mode)

Mode of the array: 1


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

